export const LOADING = 'LOADING'
export const ERROR = 'ERROR'

export const SEARCH_ITEMS = 'SEARCH_ITEMS'
export const FILTER_ITEMS = 'FILTER_ITEMS'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'

// export const TOGGLE_WISHLIST = 'TOGGLE_WISHLIST'
// export const REMOVE_WISH = 'REMOVE_WISH'

export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM'

export const UPDATE_ITEM_FORM = 'UPDATE_ITEM_FORM'
export const UPDATE_SIGNUP_FORM = 'UPDATE_SIGNUP_FORM'

export const GET_ITEMS = 'GET_ITEMS'
export const GET_MARKET_ITEMS = 'GET_MARKET_ITEMS'

export const GET_WISHLIST = 'GET_WISHLIST'

export const GET_USER_DETAILS = 'GET_USER_DETAILS'
export const GET_USER_ITEMS = 'GET_USER_ITEMS'
export const DELETE_USER_ITEM = 'DELETE_USER_ITEM'

export const BUY_ITEM = 'BUY_ITEM'

